# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BADDialog
                                 A QGIS plugin
 BAD_Burned Area Detector
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-01-24
        git sha              : $Format:%H$
        copyright            : (C) 2023 by Thomas Martinoli
        email                : th.martinoli96@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .preview_window import PreviewWindow
from .preview_fetchimages import PreviewFetchImages
from .owa_parameters_window import OwaParametersWindow

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'BAD_dialog_base.ui'))


class BADDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BADDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.Preview.clicked.connect(self.open_preview_window)
        
        self.Preview_FI_pre.clicked.connect(self.open_preview_fetchimages_pre)
        self.Preview_FI_post.clicked.connect(self.open_preview_fetchimages_post)

        self.pushButton_parameters_UC1.clicked.connect(self.open_owa_parameters_UC1_window)
        self.pushButton_parameters_UC2.clicked.connect(self.open_owa_parameters_UC2_window)


    def open_preview_window(self):
        self.preview_dialog = PreviewWindow(self)
        self.preview_dialog.show()

    def open_preview_fetchimages_pre(self):
        self.last_pre=1
        self.pushButton_FI_download_pre.setEnabled(True)
        selected_row = self.download_images_pre.currentRow()
        bbox=[float(self.lineEdit_West.text()), float(self.lineEdit_South.text()), float(self.lineEdit_East.text()), float(self.lineEdit_North.text())]
        date=self.download_images_pre.item(selected_row, 0).text()  
        time=self.download_images_pre.item(selected_row, 1).text()  
        user=self.lineEdit_User.text()
        password=self.lineEdit_Password.text()

        # Open preview with the selected image 
        self.preview_dialog = PreviewFetchImages(bbox=bbox, date=date, cloud=self.horizontalSlider_cloud_pre.value(), time=time, user=user, password=password)
        self.preview_dialog.show()

    def open_preview_fetchimages_post(self):

        self.last_post=1
        self.pushButton_FI_download_post.setEnabled(True)
        selected_row = self.download_images_post.currentRow()
        bbox=[float(self.lineEdit_West.text()), float(self.lineEdit_South.text()), float(self.lineEdit_East.text()), float(self.lineEdit_North.text())]
        date=self.download_images_post.item(selected_row, 0).text()  
        time=self.download_images_post.item(selected_row, 1).text()  
        user=self.lineEdit_User.text()
        password=self.lineEdit_Password.text()

        # Open preview with the selected image 
        self.preview_dialog = PreviewFetchImages(bbox=bbox, date=date, cloud=self.horizontalSlider_cloud_post.value(), time=time, user=user, password=password)
        self.preview_dialog.show()

    def open_owa_parameters_UC1_window(self):
        if not self.Nband:
            self.Nband = 7  # Default value if Nband is not computed
        self.preview_dialog = OwaParametersWindow(int(self.Nband))
        self.pushButton_parameters_UC1.setEnabled(False)
        if self.preview_dialog.exec_():
            self.lineEdit_OWA_a_UC1.setText(str(self.preview_dialog.result[0]))
            self.lineEdit_OWA_b_UC1.setText(str(self.preview_dialog.result[1]))
            self.pushButton_parameters_UC1.setEnabled(True)

    def open_owa_parameters_UC2_window(self):
        if not self.Nband:
            self.Nband = 7  # Default value if Nband is not computed
        self.preview_dialog = OwaParametersWindow(int(self.Nband))
        self.pushButton_parameters_UC2.setEnabled(False)
        if self.preview_dialog.exec_():
            self.lineEdit_OWA_a_UC2.setText(str(self.preview_dialog.result[0]))
            self.lineEdit_OWA_b_UC2.setText(str(self.preview_dialog.result[1]))
            self.pushButton_parameters_UC2.setEnabled(True)

 
